# Generated by Django 5.0.2 on 2024-03-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('SinCategoria', 'Sin categoría'), ('FestivalCorporativo', 'Festival Corporativo'), ('FestivalMusical', 'Festival Musical'), ('FestivalCine', 'Festival Cine'), ('FestivalGastronomico', 'Festival Gastronómico'), ('FestivalDeportivo', 'Festival Deportivo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
