# Generated by Django 5.0.2 on 2024-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0002_anfitrion_evento_usuario_delete_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
