# Generated by Django 5.0.2 on 2024-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0004_alter_evento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
