# Generated by Django 5.0.2 on 2024-03-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0005_alter_evento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Fiesta', 'Opción 1'), ('Boda', 'Opción 2'), ('Cumpleaños', 'Opción 3')], max_length=40),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=10000),
        ),
    ]
