# Generated by Django 5.0.2 on 2024-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0006_alter_evento_categoria_alter_evento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('festSinC', 'Opción 1'), ('festCorp', 'Opción 2'), ('festMusic', 'Opción 3'), ('festCien', 'Opción 4'), ('festGast', 'Opción 5'), ('festDepo', 'Opción 6')], max_length=40),
        ),
    ]
