# Generated by Django 5.0.2 on 2024-03-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0007_alter_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(max_length=40),
        ),
    ]
