# Generated by Django 5.0.2 on 2024-03-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0009_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
